### PR TITLE
suppress compiler warnings generated by clang

### PR DESCRIPTION
**Pull request by kazuho**
The commits suppresses compiler warnings due to implicit conversions between integer types.

note: for some parts of 9a0a24f it might be better to return some kind of size error rather than just converting `size_t` to `uint32_t`

### CODE REVIEW

**Comment by ymmt2005** [comment]
@kazuho 
I can confirm the first patch to fix clang warnings, but my clang 3.4-1ubuntu3
does not complain about the second patch.  What version of clang did you use?

**Comment by ymmt2005** [comment]
Adding `-Wconversion` enables these warnings, though the flag warns about tons of other codes...

**Comment by kazuho** [comment]
I am using Xcode 6.1.1 (so the clang version is presumably `Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)`).

**Comment by ymmt2005** [comment]
Picked e718871feab0f0162ced30f2a9702830aae5a844.
Replaced 9a0a24f033b1085025f10be3eb913c4f3c4d66e1 with 2e15825ddd43e9c44dfc1f15c678106097e6915b.

Thank you!

**Pull request closed without merging**
